[package]
name = "bevy_rose"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.4"
bevy = { version = "0.6", features = ["dds"] }
bevy_egui = "0.11"
bevy_rapier3d = "0.12"
bevy_polyline = "0.1"
bitflags = "1.2"
clap = "3.1"
crossbeam-channel = "0.5"
enum-map = { version = "2.0", features = ["serde"] }
image = { version = "0.23", default-features = false, features = ["dds"] }
lazy_static = "1.4.0"
log = "0.4.14"
md5 = "0.7.0"
num-traits = "0.2"
smooth-bevy-cameras = "0.2.0"
thiserror = "1.0"
tokio = { version = "1.17", features = ["rt", "net", "sync", "macros", "io-util"] }
rose-data = { git = "https://github.com/exjam/rose-offline", rev = "0ed6edd43ce024700ce4f384e68ed6455dfcef9f" }
rose-data-irose = { git = "https://github.com/exjam/rose-offline", rev = "0ed6edd43ce024700ce4f384e68ed6455dfcef9f" }
rose-file-readers = { git = "https://github.com/exjam/rose-offline", rev = "0ed6edd43ce024700ce4f384e68ed6455dfcef9f" }
rose-game-common = { git = "https://github.com/exjam/rose-offline", rev = "0ed6edd43ce024700ce4f384e68ed6455dfcef9f" }
rose-game-irose = { git = "https://github.com/exjam/rose-offline", rev = "0ed6edd43ce024700ce4f384e68ed6455dfcef9f" }
rose-network-common = { git = "https://github.com/exjam/rose-offline", rev = "0ed6edd43ce024700ce4f384e68ed6455dfcef9f" }
rose-network-irose = { git = "https://github.com/exjam/rose-offline", rev = "0ed6edd43ce024700ce4f384e68ed6455dfcef9f" }

[patch.crates-io]
bevy = { git = "https://github.com/exjam/bevy", rev = "8fa350f95cbc5c075fbff57facadfd88928bcc0a" }
bevy_ecs = { git = "https://github.com/exjam/bevy", rev = "8fa350f95cbc5c075fbff57facadfd88928bcc0a" }
bevy_polyline = { git = "https://github.com/exjam/bevy_polyline", branch = "allow_bevy_patch" }
bevy_egui = { git = "https://github.com/exjam/bevy_egui", branch = "fix_bevy_main" }
smooth-bevy-cameras = { git = "https://github.com/exjam/smooth-bevy-cameras", branch = "allow_bevy_patch" }
image = { git = "https://github.com/image-rs/image", branch = "version-0.23" }
bevy_rapier3d = { git = "https://github.com/exjam/bevy_rapier", branch = "fix_bevy_main" }

[profile.dev.package."*"]
opt-level = 3
