[package]
name = "bevy_rose"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.4"
bevy = { version = "0.6", features = ["dds"] }
bevy_egui = "0.12.1"
bevy-inspector-egui = "0.8.2"
bevy_rapier3d = "0.12"
bevy_polyline = "0.1"
bitflags = "1.2"
clap = "3.1"
crossbeam-channel = "0.5"
enum-map = { version = "2.0", features = ["serde"] }
image = { version = "0.23", default-features = false, features = ["dds"] }
lazy_static = "1.4.0"
log = "0.4.14"
md5 = "0.7.0"
num-traits = "0.2"
rand = "0.8"
smooth-bevy-cameras = "0.2.0"
thiserror = "1.0"
tokio = { version = "1.17", features = ["rt", "net", "sync", "macros", "io-util"] }
rose-data = { git = "https://github.com/exjam/rose-offline", rev = "8baad37b390c4396e8b9ec2c881a0b6b69adfeff" }
rose-data-irose = { git = "https://github.com/exjam/rose-offline", rev = "8baad37b390c4396e8b9ec2c881a0b6b69adfeff" }
rose-file-readers = { git = "https://github.com/exjam/rose-offline", rev = "8baad37b390c4396e8b9ec2c881a0b6b69adfeff" }
rose-game-common = { git = "https://github.com/exjam/rose-offline", rev = "8baad37b390c4396e8b9ec2c881a0b6b69adfeff" }
rose-game-irose = { git = "https://github.com/exjam/rose-offline", rev = "8baad37b390c4396e8b9ec2c881a0b6b69adfeff" }
rose-network-common = { git = "https://github.com/exjam/rose-offline", rev = "8baad37b390c4396e8b9ec2c881a0b6b69adfeff" }
rose-network-irose = { git = "https://github.com/exjam/rose-offline", rev = "8baad37b390c4396e8b9ec2c881a0b6b69adfeff" }

[patch.crates-io]
bevy = { git = "https://github.com/exjam/bevy", rev = "3838c808664613415e2c4a496f98ec04ebf4ee99" }
bevy_ecs = { git = "https://github.com/exjam/bevy", rev = "3838c808664613415e2c4a496f98ec04ebf4ee99" }
bevy_polyline = { git = "https://github.com/exjam/bevy_polyline", rev = "41d59d24dad7a10f5a1149c889f0108f5adc6692" }
bevy_egui = { git = "https://github.com/exjam/bevy_egui", rev = "f9a1863adf5aa6d43f4c294b79a3637a37d1c700" }
smooth-bevy-cameras = { git = "https://github.com/exjam/smooth-bevy-cameras", rev = "b9ea906f0f3c623f202d7a2a875e642845a390fc" }
image = { git = "https://github.com/image-rs/image", branch = "version-0.23" }
bevy_rapier3d = { git = "https://github.com/exjam/bevy_rapier", branch = "fix_bevy_main" }
bevy-inspector-egui = { git = "https://github.com/exjam/bevy-inspector-egui", rev = "051954a21d96c5c87c69af149f3f8e4812244d8c" }

[patch."https://github.com/exjam/rose-offline"]
rose-data = { path = "../rose-offline/rose-data" }
rose-data-irose = { path = "../rose-offline/rose-data-irose" }
rose-file-readers = { path = "../rose-offline/rose-file-readers" }
rose-game-common = { path = "../rose-offline/rose-game-common" }
rose-game-irose = { path = "../rose-offline/rose-game-irose" }
rose-network-common = { path = "../rose-offline/rose-network-common" }
rose-network-irose = { path = "../rose-offline/rose-network-irose" }

[profile.dev.package."*"]
opt-level = 3
