[package]
name = "bevy_rose"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.4"
bevy = { version = "0.6", features = ["dds"] }
bevy_egui = "0.11"
bevy_mod_picking = "0.5"
bevy_polyline = "0.1"
bitflags = "1.2"
clap = "3.1"
enum-map = { version = "2.0", features = ["serde"] }
image = { version = "0.23", default-features = false, features = ["dds"] }
lazy_static = "1.4.0"
log = "0.4.14"
nalgebra = { version = "0.25", features = ["serde-serialize"] }
rose-data = { git = "https://github.com/exjam/rose-offline", rev = "901ea4786dd98a54fb8797c5c534f1e38cb59d80" }
rose-data-irose = { git = "https://github.com/exjam/rose-offline", rev = "901ea4786dd98a54fb8797c5c534f1e38cb59d80" }
rose-file-readers = { git = "https://github.com/exjam/rose-offline", rev = "901ea4786dd98a54fb8797c5c534f1e38cb59d80" }
rose-game-common = { git = "https://github.com/exjam/rose-offline", rev = "901ea4786dd98a54fb8797c5c534f1e38cb59d80" }
rose-game-irose = { git = "https://github.com/exjam/rose-offline", rev = "901ea4786dd98a54fb8797c5c534f1e38cb59d80" }

[patch.crates-io]
bevy = { git = "https://github.com/exjam/bevy", rev = "8fa350f95cbc5c075fbff57facadfd88928bcc0a", features = ["dds"] }
bevy_ecs = { git = "https://github.com/exjam/bevy", rev = "8fa350f95cbc5c075fbff57facadfd88928bcc0a", features = ["dds"] }
bevy_mod_picking = { git = "https://github.com/exjam/bevy_mod_picking", branch = "allow_bevy_patch" }
bevy_mod_raycast = { git = "https://github.com/exjam/bevy_mod_raycast", branch = "allow_bevy_patch" }
bevy_polyline = { git = "https://github.com/exjam/bevy_polyline", branch = "allow_bevy_patch" }
bevy_egui = { git = "https://github.com/exjam/bevy_egui", branch = "fix_bevy_main" }
image = { git = "https://github.com/image-rs/image", branch = "version-0.23", default-features = false, features = ["dds"] }

[profile.dev.package."*"]
opt-level = 3
