[package]
name = "rose-offline-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.4"
arrayvec = "0.7"
async-trait = "0.1"
bevy = { version = "0.8.0-dev", features = ["dds", "tga"] }
bevy_egui = "0.14.0"
bevy-inspector-egui = "0.11.0"
bevy_polyline = "0.3.0"
bevy_rapier3d = "0.14.1"
bitflags = "1.2"
bytemuck = { version = "1.7.0", features = ["derive"] }
chrono = "0.4"
clap = "3.2"
cpal = "0.13"
crossbeam-channel = "0.5"
dolly = "0.3.1"
egui_extras = "0.18"
enum-map = { version = "2.0", features = ["serde"] }
hound = "3.4"
image = { version = "0.24", default-features = false, features = ["dds"] }
lazy_static = "1.4.0"
lewton = "0.10"
log = "0.4.14"
md5 = "0.7.0"
num-derive = "0.3"
num-traits = "0.2"
oddio = "0.5"
rand = "0.8"
serde = "1.0"
thiserror = "1.0"
tokio = { version = "1.17", features = ["rt", "net", "sync", "macros", "io-util"] }
quick-xml = { version = "0.23", features = ["serialize"] }
rose-data = { git = "https://github.com/exjam/rose-offline", rev = "b8dcc7b231399800b410f291995916f1c5713507" }
rose-data-irose = { git = "https://github.com/exjam/rose-offline", rev = "b8dcc7b231399800b410f291995916f1c5713507" }
rose-data-narose667 = { git = "https://github.com/exjam/rose-offline", rev = "b8dcc7b231399800b410f291995916f1c5713507" }
rose-file-readers = { git = "https://github.com/exjam/rose-offline", rev = "b8dcc7b231399800b410f291995916f1c5713507" }
rose-game-common = { git = "https://github.com/exjam/rose-offline", rev = "b8dcc7b231399800b410f291995916f1c5713507" }
rose-game-irose = { git = "https://github.com/exjam/rose-offline", rev = "b8dcc7b231399800b410f291995916f1c5713507" }
rose-network-common = { git = "https://github.com/exjam/rose-offline", rev = "b8dcc7b231399800b410f291995916f1c5713507" }
rose-network-irose = { git = "https://github.com/exjam/rose-offline", rev = "b8dcc7b231399800b410f291995916f1c5713507" }
rose-network-narose667 = { git = "https://github.com/exjam/rose-offline", rev = "b8dcc7b231399800b410f291995916f1c5713507" }

[patch.crates-io]
bevy = { git = "https://github.com/exjam/bevy", rev = "c0585313b183d8d1d550caba022e78a57002d8ec" }
bevy_polyline = { git = "https://github.com/exjam/bevy_polyline", rev = "c72c3bd865f1717961a547026e40d8e8d1dcbb91" }
bevy_egui = { git = "https://github.com/exjam/bevy_egui", rev = "173f2df393f88b5001e73ca82c67314327133771" }
bevy-inspector-egui = { git = "https://github.com/exjam/bevy-inspector-egui", rev = "dace3bec25a29da9fb2f18553967bb188c3428a5" }
bevy_rapier3d = { git = "https://github.com/exjam/bevy_rapier", rev = "5a8a630b22da43da219c1847c8c9665fe67ad55a" }
nalgebra = { git = "https://github.com/exjam/nalgebra", rev = "3623ab19e42eeea14a754a1fd9c29f4e9a2ce6d0" }
oddio = { git = "https://github.com/exjam/oddio", rev = "4f4eb4076c3a4068225a7c442a25e40422261c93" }


[profile.dev.package."*"]
opt-level = 3
