[package]
name = "bevy_rose"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.4"
arrayvec = "0.7"
bevy = { version = "0.7.0-dev", features = ["dds", "tga"] }
bevy_egui = "0.14.0"
bevy-inspector-egui = "0.10.0"
bevy_rapier3d = "0.13.1"
bevy_polyline = "0.1"
bitflags = "1.2"
bytemuck = { version = "1.7.0", features = ["derive"] }
clap = "3.1"
crossbeam-channel = "0.5"
egui_extras = "0.18"
enum-map = { version = "2.0", features = ["serde"] }
image = { version = "0.23", default-features = false, features = ["dds"] }
lazy_static = "1.4.0"
log = "0.4.14"
md5 = "0.7.0"
num-derive = "0.3"
num-traits = "0.2"
rand = "0.8"
smooth-bevy-cameras = "0.2.0"
thiserror = "1.0"
tokio = { version = "1.17", features = ["rt", "net", "sync", "macros", "io-util"] }
rose-data = { git = "https://github.com/exjam/rose-offline", rev = "451859431b2215294f497a76c1438675249ac3db" }
rose-data-irose = { git = "https://github.com/exjam/rose-offline", rev = "451859431b2215294f497a76c1438675249ac3db" }
rose-file-readers = { git = "https://github.com/exjam/rose-offline", rev = "451859431b2215294f497a76c1438675249ac3db" }
rose-game-common = { git = "https://github.com/exjam/rose-offline", rev = "451859431b2215294f497a76c1438675249ac3db" }
rose-game-irose = { git = "https://github.com/exjam/rose-offline", rev = "451859431b2215294f497a76c1438675249ac3db" }
rose-network-common = { git = "https://github.com/exjam/rose-offline", rev = "451859431b2215294f497a76c1438675249ac3db" }
rose-network-irose = { git = "https://github.com/exjam/rose-offline", rev = "451859431b2215294f497a76c1438675249ac3db" }

[patch.crates-io]
bevy = { git = "https://github.com/exjam/bevy", rev = "20e5f3a1e664537f1fbb06a852f8c34a8d9ce510" }
bevy_polyline = { git = "https://github.com/exjam/bevy_polyline", rev = "23572d5da68a6a2b76592092c6f0f7037b7faea3" }
bevy_egui = { git = "https://github.com/exjam/bevy_egui", rev = "e501861f04242a938790c81c24d5ed8413b5fc2a" }
bevy-inspector-egui = { git = "https://github.com/exjam/bevy-inspector-egui", rev = "b71891de2ac560ea1fe337836b03353d1dadc66a" }
bevy_rapier3d = { git = "https://github.com/exjam/bevy_rapier", rev = "75ffc00c44ef3b3cc1ebbbbb83d210ac3918a053" }
smooth-bevy-cameras = { git = "https://github.com/exjam/smooth-bevy-cameras", rev = "29bb4884f5e29f49cb599a21a0e9bc684a326402" }
image = { git = "https://github.com/image-rs/image", branch = "version-0.23" }

[profile.dev.package."*"]
opt-level = 3
