[package]
name = "rose-offline-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.4"
arrayvec = "0.7"
bevy = { version = "0.8.0-dev", features = ["dds", "tga"] }
bevy_egui = "0.14.0"
bevy-inspector-egui = "0.11.0"
bevy_polyline = "0.3.0"
bevy_rapier3d = "0.14.1"
bitflags = "1.2"
bytemuck = { version = "1.7.0", features = ["derive"] }
clap = "3.1"
crossbeam-channel = "0.5"
dolly = "0.3.1"
egui_extras = "0.18"
enum-map = { version = "2.0", features = ["serde"] }
image = { version = "0.24", default-features = false, features = ["dds"] }
lazy_static = "1.4.0"
log = "0.4.14"
md5 = "0.7.0"
num-derive = "0.3"
num-traits = "0.2"
rand = "0.8"
thiserror = "1.0"
tokio = { version = "1.17", features = ["rt", "net", "sync", "macros", "io-util"] }
rose-data = { git = "https://github.com/exjam/rose-offline", rev = "abae599d143a75a9e1559aba4891af212647547c" }
rose-data-irose = { git = "https://github.com/exjam/rose-offline", rev = "abae599d143a75a9e1559aba4891af212647547c" }
rose-file-readers = { git = "https://github.com/exjam/rose-offline", rev = "abae599d143a75a9e1559aba4891af212647547c" }
rose-game-common = { git = "https://github.com/exjam/rose-offline", rev = "abae599d143a75a9e1559aba4891af212647547c" }
rose-game-irose = { git = "https://github.com/exjam/rose-offline", rev = "abae599d143a75a9e1559aba4891af212647547c" }
rose-network-common = { git = "https://github.com/exjam/rose-offline", rev = "abae599d143a75a9e1559aba4891af212647547c" }
rose-network-irose = { git = "https://github.com/exjam/rose-offline", rev = "abae599d143a75a9e1559aba4891af212647547c" }

[patch.crates-io]
bevy = { git = "https://github.com/exjam/bevy", rev = "265052db8d0cb3597138812dc202c31f6c0518d0" }
bevy_polyline = { git = "https://github.com/exjam/bevy_polyline", rev = "c72c3bd865f1717961a547026e40d8e8d1dcbb91" }
bevy_egui = { git = "https://github.com/exjam/bevy_egui", rev = "173f2df393f88b5001e73ca82c67314327133771" }
bevy-inspector-egui = { git = "https://github.com/exjam/bevy-inspector-egui", rev = "dace3bec25a29da9fb2f18553967bb188c3428a5" }
bevy_rapier3d = { git = "https://github.com/exjam/bevy_rapier", rev = "5a8a630b22da43da219c1847c8c9665fe67ad55a" }
nalgebra = { git = "https://github.com/exjam/nalgebra", rev = "3623ab19e42eeea14a754a1fd9c29f4e9a2ce6d0" }

[profile.dev.package."*"]
opt-level = 3
