[package]
name = "bevy_rose"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.4"
arrayvec = "0.7"
bevy = { version = "0.7.0-dev", features = ["dds", "trace_tracy"] }
bevy_egui = "0.12.1"
bevy-inspector-egui = "0.8.2"
bevy_rapier3d = "0.12"
bevy_polyline = "0.1"
bitflags = "1.2"
bytemuck = { version = "1.7.0", features = ["derive"] }
clap = "3.1"
crossbeam-channel = "0.5"
enum-map = { version = "2.0", features = ["serde"] }
image = { version = "0.23", default-features = false, features = ["dds"] }
lazy_static = "1.4.0"
log = "0.4.14"
md5 = "0.7.0"
num-derive = "0.3"
num-traits = "0.2"
rand = "0.8"
smooth-bevy-cameras = "0.2.0"
thiserror = "1.0"
tokio = { version = "1.17", features = ["rt", "net", "sync", "macros", "io-util"] }
rose-data = { git = "https://github.com/exjam/rose-offline", rev = "fd53570790a9f5c062efff082a24d14e8dd615c5" }
rose-data-irose = { git = "https://github.com/exjam/rose-offline", rev = "fd53570790a9f5c062efff082a24d14e8dd615c5" }
rose-file-readers = { git = "https://github.com/exjam/rose-offline", rev = "fd53570790a9f5c062efff082a24d14e8dd615c5" }
rose-game-common = { git = "https://github.com/exjam/rose-offline", rev = "fd53570790a9f5c062efff082a24d14e8dd615c5" }
rose-game-irose = { git = "https://github.com/exjam/rose-offline", rev = "fd53570790a9f5c062efff082a24d14e8dd615c5" }
rose-network-common = { git = "https://github.com/exjam/rose-offline", rev = "fd53570790a9f5c062efff082a24d14e8dd615c5" }
rose-network-irose = { git = "https://github.com/exjam/rose-offline", rev = "fd53570790a9f5c062efff082a24d14e8dd615c5" }

[patch.crates-io]
bevy = { git = "https://github.com/exjam/bevy", rev = "75cef1bc833ba746702b08ebf9221749656d7b83" }
bevy_ecs = { git = "https://github.com/exjam/bevy", rev = "75cef1bc833ba746702b08ebf9221749656d7b83" }
bevy_math = { git = "https://github.com/exjam/bevy", rev = "75cef1bc833ba746702b08ebf9221749656d7b83" }
bevy_polyline = { git = "https://github.com/exjam/bevy_polyline", rev = "04876f83d2bee2f4369d17dcdaf47a508d8ff47d" }
bevy_egui = { git = "https://github.com/exjam/bevy_egui", rev = "4f7e7c28f34f25ca1fba45b1e6715c8a052eddc7" }
bevy-inspector-egui = { git = "https://github.com/exjam/bevy-inspector-egui", rev = "73d1f24dd9aaae7c2da4063efafbd8ffd3f531ed" }
bevy_rapier3d = { git = "https://github.com/exjam/bevy_rapier", rev = "70dc968f4cfeebf0dc68c3185f4f876f607d35b6" }
smooth-bevy-cameras = { git = "https://github.com/exjam/smooth-bevy-cameras", rev = "29bb4884f5e29f49cb599a21a0e9bc684a326402" }
image = { git = "https://github.com/image-rs/image", branch = "version-0.23" }

[profile.dev.package."*"]
opt-level = 3
